sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tQv8mg6sxfXMPTyvXgr
    access-key-secret: PPanGeHowtRTkcS2nkWgpLBJxnx4OO
    bucket-name: web-tlias-zqw
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10